[package]
name = "bc-envelope"
version = "0.11.0"
edition = "2021"
description = "Gordian Envelope for Rust."
authors = ["Blockchain Commons"]
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
repository = "https://github.com/BlockchainCommons/bc-envelope-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["data-structures", "encoding"]
documentation = "https://docs.rs/bc-envelope"

[dependencies]
dcbor = { path = "../dcbor" }
# dcbor = "0.10.0"

bc-rand = "0.1.0"

# bc-crypto = { path = "../bc-crypto" }
bc-crypto = "0.3.1"

bc-components = { path = "../bc-components" }
# bc-components = "0.6.0"

bc-ur = { path = "../bc-ur" }
# bc-ur = "0.2.1"

paste = "1.0.12"
hex = "0.4.3"
itertools = "0.11.0"
thiserror = "1.0.48"
anyhow = "1.0"
bytes = "1.5.0"

[dev-dependencies]
hex-literal = "0.4.1"
lazy_static = "1.4.0"
indoc = "2.0.0"
version-sync = "0.9"

[features]
attachment = ["known_value"]
compress = []
known_value = []
encrypt = ["known_value"]
expression = ["known_value"]
proof = []
recipient = ["encrypt"]
salt = ["known_value"]
signature = ["known_value"]
sskr = ["encrypt"]
types = ["known_value"]

default = [
    "attachment",
    "compress",
    "known_value",
    "encrypt",
    "expression",
    "proof",
    "recipient",
    "salt",
    "signature",
    "sskr",
    "types",
]
