[package]
name = "bc-envelope"
version = "0.2.1"
edition = "2021"
description = "Gordian Envelope for Rust."
authors = ["Blockchain Commons"]
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
repository = "https://github.com/BlockchainCommons/bc-envelope-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["data-structures", "encoding"]
documentation = "https://docs.rs/bc-envelope"

[dependencies]
dcbor = "0.7.6"
bc-crypto = "0.1.3"
bc-components = "0.2.1"
bc-ur = "0.1.4"
paste = "1.0.12"
hex = "0.4.3"

[dev-dependencies]
hex-literal = "0.4.1"
lazy_static = "1.4.0"
indoc = "2.0.0"
version-sync = "0.9"
